/* GreenPrompt frontend. Talks to the real backend by default.
   The demo mock is opt-in with ?mock=1 and is labelled DEMO MOCK on screen. */

// The backend origin. Change this one line to point at another host.
const BACKEND_URL = 'http://127.0.0.1:8000';

const CONFIG = { USE_MOCK_API: new URLSearchParams(location.search).get('mock') === '1', API_BASE_URL: BACKEND_URL };
const state = { sessionId: crypto.randomUUID(), mode: 'smart', selectedModel: 'small', pending: false, history: [], latest: null, lastRequest: null, summary: emptySummary() };
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
function emptySummary() { return { total_prompts: 0, small_model_percentage: 0, escalations: 0, cumulative_savings: { energy_wh: 0, co2_g: 0, water_ml: 0, cost_inr: 0 } }; }

// Visible, permanent label whenever fake answers are in use.
function renderMockBanner() {
  const existing = document.getElementById('demo-mock-banner');
  if (!CONFIG.USE_MOCK_API) { if (existing) existing.remove(); return; }
  if (existing) return;
  const banner = document.createElement('div');
  banner.id = 'demo-mock-banner';
  banner.textContent = 'DEMO MOCK - answers on this page are fake and no model was called.';
  banner.style.cssText = 'position:fixed;top:0;left:0;right:0;z-index:9999;background:#b45309;color:#fff;font:600 13px/1.4 system-ui,sans-serif;padding:8px 16px;text-align:center;letter-spacing:.02em;';
  document.body.prepend(banner);
}

// API layer: this is the only place where a browser HTTP call is made.
async function sendChat(request) {
  if (CONFIG.USE_MOCK_API) return mockSendChat(request);
  let response;
  try {
    response = await fetch(`${CONFIG.API_BASE_URL}/chat`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(request), signal: AbortSignal.timeout(30000) });
  } catch (cause) {
    const error = new Error('NETWORK_ERROR', { cause });
    error.code = cause?.name === 'TimeoutError' ? 'TIMEOUT' : 'NETWORK_ERROR';
    throw error;
  }
  if (!response.ok) {
    let payload;
    try { payload = await response.json(); } catch { /* use the normalized fallback below */ }
    const code = payload?.error?.code;
    const error = new Error(code || 'SERVER_ERROR');
    error.code = code || (response.status === 408 ? 'TIMEOUT' : 'SERVER_ERROR');
    throw error;
  }
  let data; try { data = await response.json(); } catch { const error = new Error('MALFORMED_RESPONSE'); error.code = 'MALFORMED_RESPONSE'; throw error; }
  validateResponse(data); return data;
}
function validateResponse(data) { if (!data || typeof data.answer !== 'string' || !data.impact || !data.summary || !Array.isArray(data.attempts)) { const error = new Error('MALFORMED_RESPONSE'); error.code = 'MALFORMED_RESPONSE'; throw error; } }
function mockSendChat(request) { return new Promise((resolve, reject) => setTimeout(() => { const text = request.prompt.toLowerCase(); if (text.includes('fail all') || text.includes('provider fail')) { const error = new Error('MODEL_UNAVAILABLE'); error.code = 'MODEL_UNAVAILABLE'; reject(error); return; } const tier = request.mode === 'pick' ? request.selected_model : chooseTier(text); const escalation = request.mode === 'smart' && (text.includes('binary search') || text.includes('escalat'));
  const initial = escalation ? 'small' : tier; const final = escalation ? 'medium' : tier; const unchecked = text.includes('unchecked'); const negative = text.includes('negative saving'); const values = impactFor(final, negative); const attempts = escalation ? [attempt('small','failed',196,18,104,'The first answer needed more technical detail.'),attempt('medium','passed',434,20,264,'The answer addresses the request.')] : [attempt(final, unchecked ? 'unchecked' : 'passed', final === 'small' ? 154 : final === 'medium' ? 390 : 781, 15, final === 'big' ? 422 : 134, unchecked ? 'No quality check was available.' : 'The answer addresses the request.')];
  const total = state.history.length + 1; const smallCount = state.history.filter(x => x.final_model === 'small').length + (final === 'small' ? 1 : 0); const esc = state.history.filter(x => x.escalated).length + (escalation ? 1 : 0); const previous = state.summary.cumulative_savings;
  resolve({ request_id: `mock_${Date.now().toString(36)}`, session_id: request.session_id, answer: answerFor(request.prompt, final), difficulty: difficultyFor(final), initial_model: initial, final_model: final, quality: { status: unchecked ? 'unchecked' : 'passed', reason: attempts.at(-1).quality_reason }, escalated: escalation, attempts, impact: { estimated: true, ...values.impact }, baseline: values.baseline, savings: values.savings, summary: { total_prompts: total, small_model_percentage: Math.round(smallCount / total * 100), escalations: esc, cumulative_savings: { energy_wh: previous.energy_wh + values.savings.energy_wh, co2_g: previous.co2_g + values.savings.co2_g, water_ml: previous.water_ml + values.savings.water_ml, cost_inr: previous.cost_inr + values.savings.cost_inr } } }); }, 650)); }
function chooseTier(text) { if (/distributed|architecture|multi-agent|complex|design/.test(text)) return 'big'; if (/binary|code|explain|summari[sz]e|solar/.test(text)) return 'medium'; return 'small'; }
function difficultyFor(tier) { return tier === 'small' ? 'easy' : tier === 'medium' ? 'medium' : 'hard'; }
function attempt(tier, quality_status, latency_ms, input_tokens, output_tokens, quality_reason) { return { tier, model_name: `Mock ${tier} model`, status: 'success', latency_ms, input_tokens, output_tokens, quality_status, quality_reason }; }
function impactFor(tier, negative) { const n = tier === 'small' ? .1 : tier === 'medium' ? .4 : 1; const impact = { energy_wh: .03*n, co2_g: .02181*n, water_ml: .03*n, cost_inr: .002*n }; const baseline = { energy_wh: .30, co2_g: .2181, water_ml: .30, cost_inr: .030 }; const savings = Object.fromEntries(Object.entries(baseline).map(([k,v]) => [k, +(negative ? impact[k] - v : v - impact[k]).toFixed(5)])); return { impact, baseline, savings }; }
function answerFor(prompt, tier) { const p = prompt.toLowerCase(); if (p.includes('1 + 1')) return '1 + 1 = 2.'; if (p.includes('binary search')) return 'Binary search finds an item in a sorted list by repeatedly halving the search range. It runs in O(log n) time.\n\nIn C, keep low and high indices, inspect the middle value, and discard the half that cannot contain the target.'; if (p.includes('solar')) return 'Solar panels convert sunlight into electricity through photovoltaic cells. Light excites electrons in the cell material, producing direct current; an inverter converts it into usable alternating current.'; if (p.includes('distributed') || p.includes('architecture')) return 'A distributed AI system benefits from a clear control plane, specialized workers, durable task queues, shared observability, and explicit evaluation gates. Separate orchestration from model execution so individual services can scale and fail independently.'; return `Here’s a focused response to your request. GreenPrompt selected the ${tier} tier because it best matched the apparent complexity of the task.`; }

function format(value, kind) { if (kind === 'cost') return `₹${Number(value).toFixed(3)}`; if (kind === 'energy') return `${Number(value).toFixed(2)} Wh`; if (kind === 'co2') return `${Number(value).toFixed(2)} g`; return `${Number(value).toFixed(2)} mL`; }
function qualityLabel(status) { return status === 'passed' ? 'Passed' : status === 'failed' ? 'Quality check failed' : 'Not checked'; }
function capital(value) { return value ? value[0].toUpperCase() + value.slice(1) : '—'; }
function clear(node) { node.replaceChildren(); }
function element(tag, className, text) { const el = document.createElement(tag); if (className) el.className = className; if (text !== undefined) el.textContent = text; return el; }

function renderMessage(role, text, response) { const message = element('article', `message ${role}`); const header = element('div','message-header', role === 'user' ? 'YOU' : 'GREENPROMPT'); const body = element('div','message-body',text); message.append(header,body); if (response) { const meta = element('div','message-meta'); [[capital(response.final_model),'Model'],[capital(response.initial_model),'Initial'],[capital(response.final_model),'Final'],[qualityLabel(response.quality.status),'Quality']].forEach(([value,label]) => { const item = element('span','meta'); const strong = element('strong','',`${label}: `); item.append(strong,document.createTextNode(value)); meta.append(item); }); message.append(meta); } $('#conversation').append(message); $('#conversation').scrollTop = $('#conversation').scrollHeight; }
function renderRouting(data) { const root = $('#routing-content'); clear(root); const facts = element('div','route-facts'); [['Difficulty',capital(data.difficulty)],['Initial model',capital(data.initial_model)],['Final model',capital(data.final_model)],['Quality',qualityLabel(data.quality.status)]].forEach(([label,value])=>{const item=element('div');item.append(element('span','',label),element('strong',data.quality.status === 'failed' && label === 'Quality' ? 'status-failed' : label === 'Quality' && data.quality.status === 'passed' ? 'status-good' : '',value));facts.append(item)}); root.append(facts); const attempts = element('div','attempts'); data.attempts.forEach((a,index)=>{const row=element('div',`attempt ${a.quality_status === 'failed' ? 'failed':''}`);row.append(element('strong','',`Attempt ${index+1} · ${capital(a.tier)}`),element('small','',qualityLabel(a.quality_status)));attempts.append(row)}); root.append(attempts); $('#request-status').textContent = data.escalated ? 'Escalated' : 'Complete'; }
function renderImpact(data) { const root=$('#impact-content');clear(root); const grid=element('div','impact-grid'); [['Energy',format(data.impact.energy_wh,'energy')],['CO2',format(data.impact.co2_g,'co2')],['Water',format(data.impact.water_ml,'water')],['Cost',format(data.impact.cost_inr,'cost')]].forEach(([l,v])=>{const x=element('div');x.append(element('span','',l),element('strong','',v));grid.append(x)}); const heading=element('div','savings-heading','Compared with always using Big');const saved=element('div','saved-list'); [['Energy saved',format(data.savings.energy_wh,'energy')],['Water saved',format(data.savings.water_ml,'water')],['Cost saved',format(data.savings.cost_inr,'cost')]].forEach(([l,v])=>{const x=element('div');x.append(element('span','',l),element('strong',v.startsWith('₹-')||v.startsWith('-')?'negative':'',v));saved.append(x)});root.append(grid,heading,saved); renderHighlights(data); }
function renderDetails(data, prompt) { const root=$('#request-details');clear(root);const grid=element('div','details-grid');const last=data.attempts.at(-1)||{};const rows=[['User prompt',prompt],['Request ID',data.request_id],['Difficulty',capital(data.difficulty)],['Initial model',capital(data.initial_model)],['Final model',capital(data.final_model)],['Quality status',qualityLabel(data.quality.status)],['Attempts',String(data.attempts.length)],['Latency',`${last.latency_ms ?? '—'} ms`],['Input tokens',String(last.input_tokens ?? '—')],['Output tokens',String(last.output_tokens ?? '—')]];rows.forEach(([l,v])=>{const x=element('div');x.append(element('span','',l),element('strong','',v));grid.append(x)});root.append(grid); }
function renderSummary(summary=state.summary) { $('#summary-prompts').textContent=summary.total_prompts;$('#summary-small').textContent=summary.total_prompts ? `${summary.small_model_percentage}%` : '—';$('#summary-escalations').textContent=summary.escalations;$('#summary-saved').textContent=format(summary.cumulative_savings.cost_inr,'cost');renderAnalytics(summary); }
function renderAnalytics(summary) { const metrics=$('#analytics-metrics');clear(metrics);[['Total prompts',summary.total_prompts],['Small-model usage',summary.total_prompts?`${summary.small_model_percentage}%`:'—'],['Escalations',summary.escalations]].forEach(([l,v])=>{const x=element('div');x.append(element('strong','',v),element('span','',l));metrics.append(x)});const counts=['small','medium','big'].map(t=>state.history.filter(x=>x.final_model===t).length);const total=state.history.length||1;const chart=$('#distribution-chart');clear(chart);['Small','Medium','Big'].forEach((label,i)=>{const row=element('div',`bar-row ${label.toLowerCase()}`);const track=element('div','bar-track');const fill=element('div','bar-fill');fill.style.width=`${counts[i]/total*100}%`;track.append(fill);row.append(element('span','',label),track,element('em','',`${Math.round(counts[i]/total*100)}%`));chart.append(row)});const savings=$('#savings-chart');clear(savings);[['Energy',format(summary.cumulative_savings.energy_wh,'energy')],['CO2',format(summary.cumulative_savings.co2_g,'co2')],['Water',format(summary.cumulative_savings.water_ml,'water')],['Cost',format(summary.cumulative_savings.cost_inr,'cost')]].forEach(([l,v])=>{const x=element('div');x.append(element('span','',`${l} saved`),element('strong','',v));savings.append(x)}); }
function renderHistory() { const root=$('#history-content');clear(root);if(!state.history.length){const row=element('tr','empty-row');const cell=element('td','', 'No requests in this session yet.');cell.colSpan=6;row.append(cell);root.append(row);return;} state.history.slice().reverse().forEach(item=>{const row=element('tr');const cells=[item.prompt,item.time,capital(item.difficulty),capital(item.final_model),qualityLabel(item.quality.status),format(item.savings.energy_wh,'energy')];cells.forEach((value,index)=>{const cell=element('td',index===4?'quality-chip':'',value);row.append(cell)});root.append(row)}); }
function renderError(error) { const root=$('#conversation'); const box=element('div','error-message'); box.append(element('strong','',"We couldn't complete this request."),element('p','',friendlyError(error.code)),Object.assign(element('button','retry-button','Try again'),{type:'button',onclick:()=>{if(state.lastRequest) submitPrompt(state.lastRequest.prompt)}}));root.append(box); }
function friendlyError(code) { return ({MODEL_UNAVAILABLE:'No model could complete this request. Every tier the backend tried returned an error.',TIMEOUT:'The backend did not answer within 30 seconds. It may still be starting up.',NETWORK_ERROR:`Could not reach the backend at ${BACKEND_URL}. Start it with: .venv\\Scripts\\python -m uvicorn backend.app:app --port 8000`,NOT_IMPLEMENTED:'The backend is running but a component is not finished yet (HTTP 501).',VALIDATION_ERROR:'The backend rejected this request as invalid.',INTERNAL_ERROR:'The backend hit an internal error. Check its terminal output.',MALFORMED_RESPONSE:'The backend replied in a shape this page does not understand.',SERVER_ERROR:'The backend returned an error. Check its terminal output.'})[code] || `The request failed (${code || 'unknown error'}).`; }
function setPending(pending) { state.pending=pending;$('#send-button').disabled=pending;$('#prompt-input').disabled=pending; }
async function submitPrompt(prompt) { const trimmed=prompt.trim();if(state.pending||!trimmed)return;if(trimmed.length>2000){showToast('Prompts must be 2,000 characters or fewer.');return;} state.lastRequest={prompt:trimmed};const empty=$('#empty-chat');if(empty)empty.remove();renderMessage('user',trimmed);const processing=element('div','processing','Processing your prompt...');$('#conversation').append(processing);setPending(true);$('#prompt-input').value='';autoGrow($('#prompt-input')); try{const data=await sendChat({session_id:state.sessionId,prompt:trimmed,mode:state.mode,selected_model:state.mode==='pick'?state.selectedModel:null});processing.remove();state.latest=data;state.summary=data.summary;state.history.push({...data,prompt:trimmed,time:new Intl.DateTimeFormat([], {hour:'numeric',minute:'2-digit'}).format(new Date())});renderMessage('assistant',data.answer,data);renderRouting(data);renderImpact(data);renderDetails(data,trimmed);renderSummary();renderHistory();}catch(error){processing.remove();renderError(error);$('#request-status').textContent='Could not complete';}finally{setPending(false);$('#prompt-input').focus();} }
function resetSession() { state.sessionId=crypto.randomUUID();state.history=[];state.latest=null;state.lastRequest=null;state.summary=emptySummary();clear($('#conversation'));const empty=element('div','empty-chat');empty.id='empty-chat';const leaf=element('span','empty-leaf');leaf.setAttribute('aria-hidden','true');empty.append(leaf,element('h3','', 'Start with a question'),element('p','', 'GreenPrompt will choose a proportionate model and show you why.'));$('#conversation').append(empty);$('#routing-content').replaceChildren(element('p','', 'Your latest request will appear here.'));$('#routing-content').className='placeholder-content';$('#impact-content').replaceChildren(element('p','', 'We’ll compare the request with always using the largest model.'));$('#impact-content').className='placeholder-content';$('#request-status').textContent='Waiting';$('#request-details').replaceChildren();$('#highlight-tokens').textContent='—';$('#highlight-token-rate').textContent='Backend estimate pending';$('#highlight-cost').textContent='₹0.000';$('#highlight-energy').textContent='0.00 Wh';$('#highlight-water').textContent='0.00 mL';renderSummary();renderHistory();showToast('New session started.'); }
function showToast(text){const toast=$('#toast');toast.textContent=text;toast.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.hidden=true,2400)}
function autoGrow(el){el.style.height='auto';el.style.height=`${Math.min(el.scrollHeight,160)}px`}
function setView(view){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${view}-view`)?.classList.add('active');$$('.nav-link').forEach(l=>l.classList.toggle('active',l.dataset.view===view));if(view==='how')$('#how-it-works').scrollIntoView();}

function toggleMatrix(open) {
  const drawer = $('#model-matrix');
  const scrim = $('#drawer-scrim');
  drawer.classList.toggle('open', open);
  drawer.setAttribute('aria-hidden', String(!open));
  scrim.hidden = !open;
  ['#matrix-button', '#matrix-launcher'].forEach(selector => $(selector)?.setAttribute('aria-expanded', String(open)));
  if (open) $('#matrix-close').focus();
}
function renderHighlights(data) {
  $('#highlight-cost').textContent = format(data.savings.cost_inr, 'cost');
  $('#highlight-energy').textContent = format(data.savings.energy_wh, 'energy');
  $('#highlight-water').textContent = format(data.savings.water_ml, 'water');
  const tokenSavings = data.savings?.token_savings;
  const tokenPercent = data.savings?.token_savings_percentage;
  $('#highlight-tokens').textContent = Number.isFinite(tokenSavings) ? new Intl.NumberFormat().format(tokenSavings) : '—';
  $('#highlight-token-rate').textContent = Number.isFinite(tokenPercent) ? `${tokenPercent}% fewer tokens` : 'Backend estimate pending';
}

$('#chat-form').addEventListener('submit',e=>{e.preventDefault();submitPrompt($('#prompt-input').value)});$('#prompt-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#chat-form').requestSubmit()}});$('#prompt-input').addEventListener('input',e=>autoGrow(e.target));$$('.examples button').forEach(b=>b.addEventListener('click',()=>{$('#prompt-input').value=b.textContent;autoGrow($('#prompt-input'));$('#prompt-input').focus()}));$$('.mode-button').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;$$('.mode-button').forEach(x=>x.classList.toggle('active',x===b));$('#model-picker').hidden=state.mode!=='pick'}));$$('.model-choice').forEach(b=>b.addEventListener('click',()=>{state.selectedModel=b.dataset.model;$$('.model-choice').forEach(x=>x.classList.toggle('selected',x===b))}));$$('.nav-link').forEach(link=>link.addEventListener('click',e=>{const view=link.dataset.view;if(view==='how'){return}e.preventDefault();setView(view)}));$('#new-session-button').addEventListener('click',resetSession);$('#settings-button').addEventListener('click',()=>{const menu=$('#settings-menu');menu.hidden=!menu.hidden;$('#settings-button').setAttribute('aria-expanded',String(!menu.hidden))});$('#mock-toggle').checked=CONFIG.USE_MOCK_API;$('#mock-toggle').addEventListener('change',e=>{CONFIG.USE_MOCK_API=e.target.checked;renderMockBanner();showToast(CONFIG.USE_MOCK_API?'DEMO MOCK enabled - answers are fake.':`Live backend at ${BACKEND_URL}.`);});$('#details-toggle').addEventListener('click',()=>{const detail=$('#request-details');detail.hidden=!detail.hidden;$('#details-toggle').setAttribute('aria-expanded',String(!detail.hidden));$('#details-toggle span:last-child').textContent=detail.hidden?'+':'−'});renderMockBanner();renderSummary();renderHistory();
$('#matrix-button')?.addEventListener('click',()=>toggleMatrix(true));$('#matrix-launcher').addEventListener('click',()=>toggleMatrix(true));$('#matrix-close').addEventListener('click',()=>toggleMatrix(false));$('#drawer-scrim').addEventListener('click',()=>toggleMatrix(false));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&$('#model-matrix').classList.contains('open'))toggleMatrix(false)});$$('.connection-button').forEach(button=>button.addEventListener('click',()=>showToast(`${button.dataset.provider} connection needs secure backend setup.`)));
